# Generated by Django 5.2.7 on 2025-10-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Narxi (so'mda)")),
                ('quantity_healthy', models.PositiveIntegerField(default=0, verbose_name="Sog'lom qoldiq (dona)")),
                ('quantity_defective', models.PositiveIntegerField(default=0, verbose_name='Brak qoldiq (dona)')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
    ]
