# Generated by Django 5.2.7 on 2025-10-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ismi")),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('address', models.TextField(verbose_name='Manzili')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Qarzdorligi (so'mda)")),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Dubrava', max_length=200, verbose_name='Mahsulot brendi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Eshik', max_length=200, verbose_name='Mahsulot kategoriyasi'),
            preserve_default=False,
        ),
    ]
