# Generated by Django 5.2.7 on 2025-10-18 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_customer_debt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sotuv sanasi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.customer', verbose_name='Mijoz')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi (Menejer)')),
            ],
            options={
                'verbose_name': 'Sotuv (Chek)',
                'verbose_name_plural': 'Sotuvlar (Cheklar)',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Soni')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sotuv narxi (1 dona)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product', verbose_name='Mahsulot')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.sale', verbose_name='Tegishli sotuv')),
            ],
            options={
                'verbose_name': 'Sotilgan mahsulot',
                'verbose_name_plural': 'Sotilgan mahsulotlar',
            },
        ),
    ]
