# Generated by Django 5.2.7 on 2025-10-18 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Qabul qilingan miqdor (dona)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Qabul qilingan sana')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Yuk kirimi',
                'verbose_name_plural': 'Yuk kirimlari',
            },
        ),
    ]
