# Generated by Django 5.2.7 on 2025-10-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_goodsreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('yaratildi', 'Yaratildi'), ('omborga_yuborildi', 'Omborga yuborildi'), ('yigildi', "Yig'ildi"), ('yuborildi', 'Yuborildi'), ('bron_qilindi', 'Bron qilindi'), ('bron_yuborildi', 'Bron yuborildi'), ('bron_bekor_qilindi', 'Bron bekor qilindi'), ('buyurtma_bekor_qilindi', 'Buyurtma bekor qilindi')], default='yaratildi', max_length=30, verbose_name='Sotuv statusi'),
        ),
    ]
