# Generated by Django 5.2.7 on 2025-10-20 20:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_sale_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Soni')),
                ('condition', models.CharField(choices=[('healthy', "Sog'lom"), ('defective', 'Brak')], max_length=16, verbose_name='Mahsulot holati')),
                ('reason', models.TextField(blank=True, verbose_name='Qaytarish sababi')),
                ('returned_at', models.DateField(default=django.utils.timezone.now, verbose_name='Qaytarilgan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yozuv yaratilgan sana')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.customer', verbose_name='Mijoz')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product', verbose_name='Mahsulot')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_returns', to=settings.AUTH_USER_MODEL, verbose_name='Qayd etgan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Qaytarilgan mahsulot',
                'verbose_name_plural': 'Qaytarilgan mahsulotlar',
                'ordering': ['-returned_at', '-id'],
            },
        ),
    ]
